### ISSUE TITLE
Feature Request: Automatic Index Generation in order to improve TabMon Performance

### ISSUE THREAD

**Issue by draktus** [tableau/TabMon#10]
We setup tabmon about a week ago. But as more info gets added to the DB it begins to run extremely slow <30 seconds for a query>. Anyone else seen this?

**Comment by danjrahm** [comment]
So, after a week of running tabmon against a single node Tableau Server deployment I would expect there to be around 5 or so millions rows within the postgres database (this can fluctuate wildly depending on the configuration).

This quantity of data is what's likely driving the performance down.

The best solution for this issue would probably be indexing the countersamples table. The article below shows how to create an index within postgres.
http://www.postgresql.org/docs/9.1/static/sql-createindex.html

The greatest performance improvement will probably come through indexing on timestamp.

The other method is to use Tableau Desktop to create an extract of the data.
http://onlinehelp.tableau.com/current/pro/online/windows/en-us/help.htm#extracting_create.html


We have been discussing methods to index the postgres database upon installation of TabMon. Any index we provide may be limited because we are not sure what queries TabMon users are likely to use.

**Comment by bgdnlp** [comment]
IMHO, the queries the users are most likely to use are the ones from the workbook you provide. Simply because they are already there. Optimize for those. Users that want to set up their own queries should also create the appropriate indexes themselves, if needed.

Also, providing a way to purge data older than X, either through a setting or a separate script, would be helpful. Probably most users don't care about last year's performance. And/or partitioning based on date.

**Comment by jmangue** [comment]
Automatic index creation is definitely something we've been wanting to add, but that we shelved for the 1.0 release.

Thanks a ton for the feedback.  I'm going to rename this issue and leave it open as a work item for v1.1, and will also spin up a separate open issue for your suggestion of a time-based data purge threshold option.

**Comment by danjrahm** [comment]
This is addressed in pull request #23. Closing this issue.
