### ISSUE TITLE
Question - Command prompt needs to remained open & logged in to machine where tabMon installed 

### ISSUE THREAD

**Issue by suniltikar** [tableau/TabMon#103]
Hello ,

I have a question regarding the way TabMon collect counters . When I start TabMon it starts command prompt and then I can see its collecting counters . My question is - Do I need to let command prompt open  in order to keep TabMon running . I don't want command prompt to be open all the time . second thing - Do I need to remain logged in on the machine where TabMon installed.

What will happen if I logged off from the machine where TabMon installed & what will happen if I close the command prompt will it continue to collect counters ? 

![image](https://cloud.githubusercontent.com/assets/20704119/21733286/9bf96d6a-d42b-11e6-8de9-124f116aaa2a.png)

Regards ,
Sunil Tikar

**Comment by jmangue** [comment]
Hello Sunil,

Running TabMon in console mode (as you are) is generally only advised for testing config changes or gathering metrics over a short period.  The good news is that when you installed TabMon, it registers itself as a Windows Service so that you don't have to run it in console mode.

To start the TabMon service, see the directions at the bottom of page 6 of the [user guide](https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf).

-Justin

**Comment by jmangue** [comment]
Closing this one out, as it has been answered.

Sunil, please reopen this if you need any more help on this issue.
