### ISSUE TITLE
tabmon - missing counters

### ISSUE THREAD

**Issue by JeffStrauss18** [tableau/TabMon#104]
Prior to upgrading to Tableau 10.1.3, we were on 9.2.6 and we were using the original version of TABMON with our own custom Tableau viz dashboard.  It appears that the following counters are no longer available in the new TABMON.  Can you confirm, or tell me whether these can still be retrieved some how?  We would like to continue capturing these.  Thanks, Jeff

    <Source name="vizportal" startport="8900" endport="8999">
      <TableauHealth>
        <Category name="Get View" path="name=webclientappservice.getview">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="User Login" path="name=webclientappservice.login">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
      </TableauHealth>

**Comment by jmangue** [comment]
Hi Jeff,

In Tableau Server 9.3 & 10.0, many JMX counters were renamed or removed (and many new ones added!), unfortunately including the ones you listed.

If you are using the newest version of TabMon, there is a [Counters.config file for 10.0](https://github.com/tableau/TabMon/blob/master/TabMon/Resources/Configurations/9.3%20-%2010.0/Counters.config) you can update to that includes login data:

```xml
<Category name ="Login" path="00=api,01=webClient,name=login">
       <Counter name="ExceptionCount" />
       <Counter name="InvocationCount" />
</Category>
<Category name ="SSPI Login" path="00=api,01=webClientAuth,name=sspiLogin">
       <Counter name="ExceptionCount" />
       <Counter name="InvocationCount" />
</Category>
```

Updating to this counters.config file will probably require some changes in your custom workbook due to  all of the JMX counter changes.  We tried to keep the TabMon schema as stable as possible, but the scope of JMX changes in Server required it to change in many places.

**Comment by jmangue** [comment]
Closing this one out, please reopen if you need further help.
