### ISSUE TITLE
TabMon Installation on anothoer server

### ISSUE THREAD

**Issue by hyungchoi** [tableau/TabMon#115]
Is it possible to install it on another Windows server instead of the Tableau Server? Is there any configuration steps that I need to do so it can monitor Tableau Server that is running on another server?

**Comment by rahulmotwani** [comment]
Hi @hyungchoi,

Yes, it is possible to install TabMon on another Windows server instead of the machine hosting Tableau Server. In order to do this, look under the 'Advanced Configuration Options - Remote Polling setup' section in the Installation guide located @ https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf 

Let us know if you you still need help.

**Comment by jmangue** [comment]
Closing this one out as answered.
