### ISSUE TITLE
TabMon sample workbook for v.10 cannot be opened 

### ISSUE THREAD

**Issue by nemecjan-jenn** [tableau/TabMon#122]
Hello!

I tried several times to download sample workbook for version 10 and open it in Tableau desktop on different projects, version 10.0 and 10.2, but not successfull.
Latest error message was on 10.2 version, following:

 
![image](https://user-images.githubusercontent.com/29305545/26975586-b699554a-4d20-11e7-8e8c-698e0621c628.png)

Can you, please, help, what I'm doing wrongly or how can I fix it?
Thanks ;)

**Comment by danjrahm** [comment]
Hello,

The sample workbook should be included with TabMon install, try using these. In order to find the workbooks please log on to the TabMon computer then navigate to a directory like this:
<TABMON INSTALL ROOT>\TabMon\Resources\Sample Workbooks

This directory will have all of the updated workbooks. 
Please let me know if there are any issues with this.

Thanks,
-Dan

**Comment by nemecjan-jenn** [comment]
Hi!

Thank you very much for your answer! It was my fault when downloading
sample workbook wrongly.
Now I'm able to republish TabMon workbook without any issue.

Have a nice day!
J+

**Comment by danjrahm** [comment]
I'm glad everything worked out! I'll close this issue now!
