### ISSUE TITLE
Logging to db by IP only now in the machine column of countersamples?

### ISSUE THREAD

**Issue by slewt** [tableau/TabMon#152]
Looks like in TabMon v1.2 is the machine column only going to be by IP or is hostname an option I have just missed somewhere? I have tried a couple of different values for computerName and removing address attribute (which caused the service to fail on start) to get the old format.

I personally preferred displays by hostname and may end up writing a trigger to modify the incoming entries if I've missed a config item.

Thanks,

**Comment by sqllackey** [comment]
I also needed to add IP addresses for Tabmon to come up in 1.2.  This is a departure from machinename only in 1.0

**Comment by danjrahm** [comment]
Hello, 

The Machine column is determined by the the "address" attribute in the host lines. The "address" attribute can be either the IP address or the FQDN. "ComputerName" should be the actual computer name of the host and will not affect what is displayed in the workbook.

We made this change in order to resolve issue #99. 

In order to get the old format in the workbook, I suggest changing "address" to the FQDN for the server.

Let me know if that works,
Dan

**Comment by slewt** [comment]
Thanks, that was it. Had worked by hostname in v1.1 prior. Putting the hostname back into address field, got desired results.
