### ISSUE TITLE
TabMon doesn't collect correctly perfmon counters from part of machines

### ISSUE THREAD

**Issue by LightTab** [tableau/TabMon#180]
Hello,

I have following issue with TabMon:
On some Tableau machines it collects correctly perfmon counters, on some not. For example, I have one machine for which it only collects perfmon counters for postgres (lot of instances, from postgres to postgres#39) and tabprotosrv (about 11 instances) but everywhere is zero value. No other perfmon counters collected. It suddenly stopped to work correctly. As I know there is possibility that processes configuration between primary and worker node has been changed, but I am not sure if this should have any impact.

TabMon is collecting information from 8 machines which are divided into groups of two: primary + worker node. 

Thank you in advance for your help.

**Comment by danjrahm** [comment]
Hello,

It is normal for TabMon to collect multiple numbered postgres and tabprotosrv processes. This is because at certain times there may be a large amount of postgres and tabprotosrv processes.

Once collected the first time, TabMon assumes those numbered processes still exist. Every subsequent poll after will try to collect values for those non-existent processes. If the process doesn't exist it will fill the value with 0.

As for why no other processes are being collected, I am not sure at the moment. Please attach the logs located at <INSTALL ROOT>\TabMon\Logs\TabMon.log

This should give me enough to start.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello,

Due to thread inactivity I am going to close this. Please let me know if the issue persists. 

Thanks,
Dan
