### ISSUE TITLE
CPU Utilization by Service view only shows four items in the legend (Gateway, Postrges, tabprotosrv, and tabsvc) 

### ISSUE THREAD

**Issue by sophistafunk** [tableau/TabMon#203]
Hi Dan,
Grant Eaton was onsite working with us on TabMon with Tableau 2018.2.3 and he found it wasn't collecting all the data points for all services. He said you requested I posted here for help troubleshooting the issue. Could you tell us what we need to do to get to the bottom of these? We are expecting to see data collected for a wide variety of Tableau services, not just Gateway, Postgres, tabporotosrv, tabsvc.

![tabmon_github_error_pic](https://user-images.githubusercontent.com/35550856/49769977-38eb3500-fc97-11e8-9941-de69586d473c.PNG)
![tableau_server_topology](https://user-images.githubusercontent.com/35550856/49770024-7223a500-fc97-11e8-8bf4-f37de4eb4bd1.png)

**Comment by danjrahm** [comment]
Hello @sophistafunk,

I believe this issue was due to a bug in the workbook. I uploaded the fixed workbook (in a zip file) to issue #204.

Please let me know if this issue persists after using the new workbook. If it does, we will continue troubleshooting the issue. Until then, I am going to close this.

Thanks,
Dan
