### ISSUE TITLE
已升级到Tableau2018.3版本如何使用Ta

### ISSUE THREAD

**Issue by tmac2100** [tableau/TabMon#218]
2019-03-04 08:48:42,874 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: Failed to establish a connection to 'localhost'.

**Comment by danjrahm** [comment]
Hello @tmac2100,

In order to investigate this issue I will need the following information.

1. Tableau Server version that you are trying to monitor.
2. TabMon version.
3. TabMon logs. Located here: <TABMON ROOT>\TabMon\Logs\TabMon.log.txt
4. The TabMon config file. Located here: <TABMON ROOT>\TabMon\Config\TabMon.config

Feel free to obfuscate any personal information in the logs or config file.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello,

I am going to close this issue due to inactivity. If this is still occurring, please send the requested info above and I will reopen this issue.

Thanks,
Dan
