### ISSUE TITLE
user Logins are not shown in the Viz

### ISSUE THREAD

**Issue by vishwakar** [tableau/TabMon#5]
Hi 

I was able to set it up and I can see some data on the rest of the tabs , However There seems to be some issue on the Logins Tab as it doesnt show any data which is akward.

![login](https://cloud.githubusercontent.com/assets/7689926/10646597/ea7afdd2-7801-11e5-8e7b-97d311c4c969.JPG)

Thanks
Vishwanath

**Comment by jmangue** [comment]
Hi Vishwa, thanks for trying out TabMon!
 
Fortunately there is a really easy fix for the issue you're hitting.  We call this out in the FAQ/Troubleshooting section of the user guide, but for convenience I'm pasting it here also:
 
"Between version 9.0 and 9.1 of Tableau Server, we changed the internal names of many of our JMX counters.  The Counters.config file that ships with TabMon supports the new 9.1+ naming conventions.  To adjust for the old naming system, simply open Counters.config and do a find and replace all, substituting the term "webclientappservice" with "iwebclientappservice.""
 
If you do that and then stop & restart TabMon, you should see the Login counters being pulled in correctly.
 
Closing this out as a GitHub issue since it is not a code defect, but if you're still having trouble you can post on the Server Administration community and we'll try and help. :)

-Justin
