### ISSUE TITLE
TabMon- CSV file naming convention and data issue

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#58]
Hi 

I am using csv file as data source in TabMon. A new csv file is generated whenever I stop and start Tabmon. The file which is getting generated has file name including date and time. If I want to control filename is that possible?

Also, I checked the csv file data. It is gathering large amount of data. Is there a way that I can control data?

Thanks 
Rishabh

**Comment by danjrahm** [comment]
Hello Rishabh,

The naming convention for the TabMon CSVs are automatically generated when the TabMon service is started. We do this to avoid overwriting older CSVs. In order to control the filename I would rename the files once they are complete and the service is no longer running. This can be done manually or using some sort of scheduled task.

As far as the amount of data that is collected, we can control that a few different ways.
Option one: Decrease the poll rate. (This can be done in the TabMon config).
Option two: Remove unwanted counters from the Counters config. 

We do have plans to implement a semi sparse data structure. This should also decrease the amount of data that is collected. 

If you have any other questions let me know. I am now going to close this issue.

Thanks,
Dan

**Comment by rishabh1991** [comment]
Hi Dan,

Thanks a lot for help on this.

Another issue,

When I am connecting the data source the visualization on worksheet is showing the updated data.But when I am clicking on data source on view data option it is showing back date data.How to resolve this one?
Also, Is there a limit that for maximum size of csv file getting generated?

My main requirement is that csv file should contain data for one week. After the completion of week automatically a new csv file should get generated and data should be updated in that for rest of the week.
How to achieve this result?

Thanks 
Rishabh
