### ISSUE TITLE
TabMon- Data View issue

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#59]
HI

When I am connecting the data source the visualization on worksheet is showing the updated data.But when I am clicking on data source on view data option it is showing back date data.How to resolve this one?
Also, Is there a limit that for maximum size of csv file getting generated?

My main requirement is that csv file should contain data for one week. After the completion of week automatically a new csv file should get generated and data should be updated in that for rest of the week.
How to achieve this result?

Thanks 
Rishabh

**Comment by danjrahm** [comment]
Hello,

How is the datasource being replaced? If the datasource is being replaced using the "Replace Datasource" functionality in Tableau Desktop this should not occur. This article should help with replacing the datasource so the correct date is seen:
http://kb.tableau.com/articles/knowledgebase/replacing-data-source

As for the CSV size, I do not believe CSVs have a max size (other than disk space).

In order to achieve you main requirement I would do 1 of the following.
1. Start the Tabmon Service and create a script that stops/starts it. I would then schedule that script to run once a week.
2. Have TabMon output to Postgres (as mentioned in the user guide). To gain 1 weeks worth of data I recommend either filtering for the last weeks worth of data in Tableau Desktop or I would create a trigger in postgres that delete any rows older than 7 days when data is inserted into postgres.

If there are any other questions please let me know. I am now going to close this.

**Comment by rishabh1991** [comment]
Hi Dan,

I am creating extract(incremental) from CSV file and using the same data source so no need of replacing the data source as it is getting updated regularly and the visualization in worksheet is also correct.

But when I am viewing data from worksheet it is not showing updated data.

How to resolve this issue?(PFA)
![data_issue](https://cloud.githubusercontent.com/assets/17762245/14383605/d5f66116-fdb3-11e5-973b-46b5cdf48f14.png)


Thanks 
Rishabh

**Comment by danjrahm** [comment]
Hello,

It's likely that the data is correct and updating. From the screenshots it looks like both of the datasets are filtered to the top 10,000 lines. 

Entering a larger number into the top left text box (10 million or so) should increase the amount of data being shown.

If there are any other questions let me know.

Thanks,
Dan
