### ISSUE TITLE
No visuals for workernodes 

### ISSUE THREAD

**Issue by Shobananpa** [tableau/TabMon#75]
Hi Team,

I'm not able to see any visuals for our worker nodes post tabmon installation, I have attached the log file for reference, please help me to identify and get this running.
[tabmon error log - 27th June.txt](https://github.com/tableau/TabMon/files/335348/tabmon.error.log.-.27th.June.txt)

Thanks,
Shoba

**Comment by jmangue** [comment]
Hi Shoba,

It looks like Perfmon data is successfully being gathered, but JMX data is not.  This could be due to a few things:

- JMX may not be enabled on Tableau Server.  (It sounds like you've enabled JMX, so we can skip this one in your case -- just mentioning it in case it helps others)
- JMX may be running on non-default ports, in which case you'll need to update TabMon's Counters.config file to point to the correct ports.
- Polling JMX may be getting blocked by some kind of firewall or security software.

TabMon uses a rolling log file system and the log you posted does not include the messages from service start, when any error messages about JMX would be displayed.

Can you restart the TabMon service, let it run for a couple minutes, and then send me the new log?  Thanks.
