### ISSUE TITLE
Feature Request: unattended installation with arguments

### ISSUE THREAD

**Issue by stmarier** [tableau/TabMon#80]
Hi,

I'm not really a windows person, so there might already be a solution for this, but it would be really great if I could pull an MSI from the releases directory instead of an exe.

It's my current understanding that, with the exe (which is just a bootstrapper for the msi?), I'm unable to pass arguments into the installer.

What I'd really, really like to do is just be able to call the installer with no UI (possible already with /q), but also set `OptionInstallPostgres` to 0 because I'll be pointing tabmon towards an external database.

Please let me know if I need to clarify anything as this isn't something I typically deal with or know a lot about.  Thanks a bunch.

**Comment by jmangue** [comment]
This is a bit weird, but you can actually do a silent install using the bootstrapper with the following command:

`InstallTabMon.exe /install /q OptionInstallPostgres=""`

(Substitute /q with /p if you still want to see progress bars)

Setting OptionInstallPostgres to 0 will still install it due to an idiosyncracy in the way WiX evaluates string variables from the command line -- any non-empty string is interpreted as "true".

That said, releasing the MSI as well is something we can totally do in the next release.. there is no reason not to.

**Comment by stmarier** [comment]
Ah - awesome, thanks for clearing that up for me!  I had attempted that, but noted that it was still installing postgres anyway, so I assumed I had done something wrong. :)  Windows installers have always been pretty mysterious to me.

Appreciate the note about the .NET dependency checking as well.  I'll look forward to 1.1, and handle postgres with a post-install cleanup script until then.

Thanks for the quick response and all of your help!

**Comment by jmangue** [comment]
No problem!  From your reply, I think my answer may have been unclear so I'm going to restate --

Rather than install Postgres and then have to script a clean up afterwards, you can do a silent install that skips the Postgres install altogether using `InstallTabMon.exe /install /q OptionInstallPostgres=""`

The `OptionInstallPostgres=""` bit disables installation of Postgres.

**Comment by jmangue** [comment]
I had some second thoughts on this after reviewing the MSI...

The MSI does any dependency checking, has an ugly UI, and putting it up on the releases page might confuse some people and they may choose to download it over the bootstrapper.

Given that all the args to the MSI are also overridable in the bootstrapper using the syntax I mentioned above, I see no reason the MSI needs to be posted... closing this out.
