### ISSUE TITLE
TabMon causing CPU issues on the worker node

### ISSUE THREAD

**Issue by ChaitanyaSomanchi** [tableau/TabMon#89]
Hi,

We have a 3 node environment and running TabMon on a different host other than these 3 nodes. When ever we start TabMon after 30mins one of the node becomes unresponsive and when we look at the task manager TabMon will be consuming more CPU than usual.

Just wanted to check if we are only seeing this issue or anyone else too and Will TabMon cause latency issues ?

Thanks
Chaitanya

**Comment by jmangue** [comment]
Hi Chaitanya,

TabMon should be pretty lightweight; I have not heard of any other occurrences with TabMon causing a resource issue.

Does the node still become unresponsive even if TabMon is not running?

**Comment by ChaitanyaSomanchi** [comment]
Thanks for the quick response Justin.

When we stop TabMon the node gets back to its normal.

**Comment by jmangue** [comment]
That is odd.  TabMon is only interacting with the node using Perfmon and JMX, both of which are pretty standard lightweight APIs and should not be significantly impacting performance.

One thing to try is to raise the polling interval (in TabMon.config) so that TabMon samples counters from that node less often.  The default is 30 seconds, which is pretty aggressive -- you might want to raise it up to somewhere in the 60-300 second range.

**Comment by jmangue** [comment]
Hi Chaitanya, are you still experiencing this issue after upping the polling interval?

**Comment by ChaitanyaSomanchi** [comment]
Hi Justin,

No, after upping the polling interval we are not seeing any CPU issues

**Comment by jmangue** [comment]
Great to hear that.  Closing this issue out.
